import {SubjectsModel} from "./subjectsModel";
import {LMSModel} from "./lmsModel";
import {Validator} from "./validator";
import {TeachersModel} from "./teachersModel";
import {PupilsModel} from "./pupilsModel";
import {GroupsModel} from "./groupsModel";
import {GradeBooksModel} from "./gradebooksModel";
export {SubjectsModel};
export {LMSModel};
export {TeachersModel};
export {Validator};
export {PupilsModel};
export {GroupsModel};
export {GradeBooksModel};